CREATE TABLE BLOCKED_DATA(
ID INT NOT NULL AUTO_INCREMENT,
Blocked VARCHAR(20) NOT NULL,
Blocker VARCHAR(20) NOT NULL,

PRIMARY KEY (ID),
FOREIGN KEY (Blocked) REFERENCES USER(Username) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (Blocker) REFERENCES USER(Username) ON DELETE CASCADE ON UPDATE CASCADE
);