CREATE TABLE LIKED_DATA(
ID INT NOT NULL AUTO_INCREMENT,
IDTweet INT NOT NULL,
LikedBy VARCHAR(20) NOT NULL,

PRIMARY KEY (ID),
FOREIGN KEY (IDTweet) REFERENCES TWEET(ID) ON UPDATE CASCADE ON DELETE CASCADE,
FOREIGN KEY (LikedBy) REFERENCES USER(Username) ON UPDATE CASCADE ON DELETE CASCADE
);