CREATE TABLE USER(
Username VARCHAR(20) NOT NULL,
Name VARCHAR(20) NOT NULL,
Surname VARCHAR(20) NOT NULL,
Pass VARCHAR(128) NOT NULL,
Date_Of_Birth DATE NOT NULL,
Date_Of_Sub DATE NOT NULL,
Bio VARCHAR(64)
);