CREATE TABLE LIKED_DATE(
ID INT NOT NULL AUTO_INCREMENT,
IDTweet INT NOT NULL,
LikedBy VARCHAR(20) NOT NULL,

PRIMARY KEY (ID),
FOREIGN KEY (IDTweet) REFERENCES TWEET(ID),
FOREIGN KEY (LikedBy) REFERENCES USER(Username)
);