CREATE TABLE MESSAGE(
ID INT NOT NULL AUTO_INCREMENT,
IDTweet INT,
Content VARCHAR(256),
Sender VARCHAR(20),
Receiver VARCHAR(20),
SendTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

PRIMARY KEY (ID),
FOREIGN KEY (IDTweet) REFERENCES TWEET(ID) ON UPDATE CASCADE ON DELETE CASCADE,
FOREIGN KEY (Sender) REFERENCES USER(Username) ON UPDATE CASCADE ON DELETE CASCADE,
FOREIGN KEY (Receiver) REFERENCES USER(Username) ON UPDATE CASCADE ON DELETE CASCADE
);