CREATE TABLE FOLLOWING_DATA(
ID INT NOT NULL AUTO_INCREMENT,
Followed VARCHAR(20) NOT NULL,
Follower VARCHAR(20) NOT NULL,

PRIMARY KEY (ID),
FOREIGN KEY (Followed) REFERENCES USER(Username),
FOREIGN KEY (Follower) REFERENCES USER(Username)
);